project:
  type: website

website:
  title: "Bloggeando Datos"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhonatanz 
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



