project:
  type: website

website:
  title: "Bloggeando Datos"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhonatanz 
  page-navigation: true
format:
  html:
    theme:
      - minty      
    css: styles.css



